### ISSUE TITLE
Remove use of Node.js modules

### ISSUE THREAD

**Issue by zenflow** [jshttp/content-disposition#44] opened 2022-04-29 19:22 UTC
Webpack v5 removed the Nodejs polyfills for the web client builds.

This package `require`s the `path` module.

That means if your frontend project is using this package and you want to upgrade to Webpack v5, you will have to install [node-polyfill-webpack-plugin](https://www.npmjs.com/package/node-polyfill-webpack-plugin).

Could we replace this line
https://github.com/jshttp/content-disposition/blob/73bf21e7c3f55f754932844584061027767289f4/index.js#L22
with a custom implementation of `basename` function?
Would that be accepted?

**Comment by dougwilson** [comment] 2022-04-29 19:25
Hi @zenflow thank you for your issue! This is a duplicate of #32 most likely. If not, please let me know and I can re-open it.

**Comment by zenflow** [comment] 2022-04-29 19:26
@dougwilson Yes, it is.. Sorry about that! Thanks!

**Closed by dougwilson** 2022-04-29 19:25 UTC

**Comment by dougwilson** [comment] 2022-04-29 19:28
No problem! And as for the issue itself, I think you'll just run in to more after `path`, as this module also uses `safe-buffer`, which itself uses the Node.js `buffer` module, which is also a Node.js built-in I assume you'd need to polyfill as well.
