### ISSUE TITLE
Cyrillic filenames not supported

### ISSUE THREAD

**Issue by nosovk** [jshttp/content-disposition#41] opened 2022-02-02 14:23 UTC
filename: ```Договір вiд 02.02.2022.pdf```
will be converted to:
```contentDisposition:  attachment; filename="??????? ?i? 02.02.2022.pdf"; filename*=UTF-8''%D0%94%D0%BE%D0%B3%D0%BE%D0%B2%D1%96%D1%80%20%D0%B2i%D0%B4%2002.02.2022.pdf```
which is invalid

**Comment by dougwilson** [comment] 2022-02-02 14:37
Hi, thank you for the report. What about it is invalid? The name is encoded according to the spec. If it is that you don't want the latin fallback use `{ fallback: false }`.

**Comment by dougwilson** [comment] 2022-02-02 15:16
Strange. This library doesn't generate any kind of error like that, so I'm not sure what it means. Are you able to provide steps where I can reproduce that error?

**Comment by nosovk** [comment] 2022-02-03 21:24
I just avoided that problem by adding transliteration for non English symbols

**Comment by dougwilson** [comment] 2022-04-29 19:30
Hi @nosovk I'm going to close this issue because there doesn't seem to be any action for us to take.

**Closed by dougwilson** 2022-04-29 19:30 UTC
Labels: investigate

**Comment by nosovk** [comment] 2022-05-02 10:53
yep, I avoided it by transliteration, and have no intention to debug what exactly wrong inside lib for now.

**Comment by AIHI** [comment] 2023-04-14 19:09
According to my observations,  if the Cyrillic alphabet has more than 42-43 characters, the library starts to work incorrectly
[Видео](https://drive.google.com/open?id=184L4q6HZy8CcXr-oryMtl3e1vxaY8H5n&authuser=vadimesed%40gmail.com&usp=drive_fs)
