### ISSUE TITLE
Allow to be built with webpack, use only some features.

### ISSUE THREAD

**Issue by ievgennaida** [jshttp/content-disposition#45] opened 2022-07-21 06:58 UTC
I would like to use this library on  a frontend to parse content disposition header and get only filename from it.
Unfortunately at the moment it's not possible to do while web pack cannot import modules that are not even suppose to be used:

var basename = require('path').basename
var Buffer = require('safe-buffer').Buffer

```

Module not found: Error: Can't resolve 'path' in '...\node_modules\content-disposition'

BREAKING CHANGE: webpack < 5 used to include polyfills for node.js core modules by default.
This is no longer the case. Verify if you need this module and configure a polyfill for it.

If you want to include a polyfill, you need to:
	- add a fallback 'resolve.fallback: { "path": require.resolve("path-browserify") }'
	- install 'path-browserify'
If you don't want to include a polyfill, you can use an empty module like this:
	resolve.fallback: { "path": false }


ERROR in ./node_modules/content-disposition/node_modules/safe-buffer/index.js 4:13-30
Module not found: Error: Can't resolve 'buffer' in '..\content-disposition\node_modules\safe-buffer'
```

Would be nice if those modules are imported only when they are really required and allow to use regex part only separately.

**Comment by dougwilson** [comment] 2022-07-21 07:01
This is a duplicate of #44 most likely. If not, please let me know and I can re-open it.

**Closed by dougwilson** 2022-07-21 07:01 UTC
